'use client';

import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@supabase/supabase-js';
import './styles.css';

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
const money = (v) => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
const date = (v) => v ? new Date(v+'T00:00:00').toLocaleDateString('pt-BR') : '—';
const typeLabel = (v) => ({sale:'Compra',payment:'Pagamento',credit:'Crédito'})[v] || v;
const methodLabel = (v) => ({credit:'Conta',pix:'PIX',cash:'Dinheiro',card:'Cartão',check:'Cheque',transfer:'Transferência'})[v] || v || '—';
const statusLabel = (v) => v === 'cancelled' || v === 'void' ? 'CANCELADO' : 'ATIVO';
const emptyCustomer = {name:'',document:'',phone:'',credit_limit:'',notes:'',store_name:''};
const emptyReportFilters = {from:'',to:'',customer_id:'',customer_group:'',kind:'all'};
const emptyTransaction = {customer_id:'',type:'sale',amount:'',payment_method:'credit',description:'',transaction_date:''};

export default function Home(){
 const [session,setSession]=useState(null),[page,setPage]=useState('dash'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[customers,setCustomers]=useState([]),[tx,setTx]=useState([]),[report,setReport]=useState([]),[loading,setLoading]=useState(false);
 const [form,setForm]=useState({customer_id:'',type:'sale',amount:'',payment_method:'credit',description:''});
 const [customerForm,setCustomerForm]=useState(emptyCustomer),[editingCustomer,setEditingCustomer]=useState(null),[customerModal,setCustomerModal]=useState(false);
 const [transactionForm,setTransactionForm]=useState(emptyTransaction),[editingTransaction,setEditingTransaction]=useState(null),[transactionModal,setTransactionModal]=useState(false);
 const [reportFilters,setReportFilters]=useState(emptyReportFilters);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session) load()},[session]);
 async function load(){setLoading(true);const [{data:c},{data:t},{data:r}]=await Promise.all([supabase.from('customers').select('id,name,document,phone,credit_limit,notes,store_name,active').eq('active',true).order('name'),supabase.from('customer_transactions').select('id,customer_id,type,amount,payment_method,transaction_date,description,status').order('transaction_date',{ascending:false}).limit(1000),supabase.from('report_customer_account_summary').select('*').order('customer_name')]);setCustomers(c||[]);setTx(t||[]);setReport(r||[]);setLoading(false)}
 async function login(e){e.preventDefault();setError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message)}
 async function save(e){e.preventDefault();setError('');const amount=Number(form.amount);if(!form.customer_id||!amount||amount<=0){setError('Selecione o cliente e informe um valor válido.');return}const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('customer_transactions').insert({customer_id:form.customer_id,type:form.type,amount,payment_method:form.payment_method,description:form.description||null,transaction_date:new Date().toISOString().slice(0,10),created_by:user?.id,status:'posted'});if(error){setError(error.message);return}setForm({customer_id:'',type:'sale',amount:'',payment_method:'credit',description:''});await load();setPage('dash')}
 function openEditTransaction(transaction){if(transaction.status!=='posted')return;setEditingTransaction(transaction);setTransactionForm({customer_id:transaction.customer_id||'',type:transaction.type||'sale',amount:transaction.amount??'',payment_method:transaction.payment_method||'credit',description:transaction.description||'',transaction_date:transaction.transaction_date||''});setError('');setTransactionModal(true)}
 function closeTransactionModal(){setTransactionModal(false);setEditingTransaction(null);setTransactionForm(emptyTransaction);setError('')}
 async function saveTransaction(e){e.preventDefault();setError('');const amount=Number(transactionForm.amount);if(!transactionForm.customer_id||!amount||amount<=0||!transactionForm.transaction_date){setError('Informe cliente, data e um valor válido.');return}const {error}=await supabase.from('customer_transactions').update({customer_id:transactionForm.customer_id,type:transactionForm.type,amount,payment_method:transactionForm.payment_method,description:transactionForm.description.trim()||null,transaction_date:transactionForm.transaction_date}).eq('id',editingTransaction.id).eq('status','posted');if(error){setError(error.message);return}closeTransactionModal();await load()}
 async function cancelTransaction(transaction){if(transaction.status!=='posted')return;const customerName=names.get(transaction.customer_id)||'este cliente';if(!window.confirm(`Cancelar o lançamento de ${money(transaction.amount)} de ${customerName}?\n\nO lançamento não será apagado do banco: ele ficará marcado como CANCELADO e deixará de entrar nos cálculos e saldos.`))return;setError('');const {error}=await supabase.from('customer_transactions').update({status:'cancelled',correction_reason:'Lançamento cancelado pelo usuário'}).eq('id',transaction.id).eq('status','posted');if(error){setError(error.message);return}await load()}
 function openNewCustomer(){setEditingCustomer(null);setCustomerForm(emptyCustomer);setError('');setCustomerModal(true)}
 function openEditCustomer(customer){setEditingCustomer(customer);setCustomerForm({name:customer.name||'',document:customer.document||'',phone:customer.phone||'',credit_limit:customer.credit_limit??'',notes:customer.notes||'',store_name:customer.store_name||''});setError('');setCustomerModal(true)}
 function closeCustomerModal(){setCustomerModal(false);setEditingCustomer(null);setCustomerForm(emptyCustomer);setError('')}
 async function saveCustomer(e){e.preventDefault();setError('');if(!customerForm.name.trim()){setError('Informe o nome do cliente.');return}const payload={name:customerForm.name.trim(),document:customerForm.document.trim()||null,phone:customerForm.phone.trim()||null,credit_limit:customerForm.credit_limit===''?0:Number(customerForm.credit_limit),notes:customerForm.notes.trim()||null,store_name:customerForm.store_name.trim()||null};const query=editingCustomer?supabase.from('customers').update(payload).eq('id',editingCustomer.id):supabase.from('customers').insert({...payload,active:true,deactivated_at:null,deactivated_by:null});const {error}=await query;if(error){setError(error.message);return}closeCustomerModal();await load()}
 async function hideCustomer(customer){if(!window.confirm(`Ocultar o cliente ${customer.name}? Ele não aparecerá mais na lista de clientes ativos nem no lançamento de novas compras.`))return;setError('');const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('customers').update({active:false,deactivated_at:new Date().toISOString(),deactivated_by:user?.id||null}).eq('id',customer.id);if(error){setError(error.message);return}await load()}
 const names=useMemo(()=>new Map(customers.map(c=>[c.id,c.name])),[customers]);
 const reportNames=useMemo(()=>new Map(customers.map(c=>[c.id,c.store_name||c.name])),[customers]);
 const customerGroupById=useMemo(()=>new Map(customers.map(c=>[c.id,(c.store_name||'').split(' • ')[0].trim()])),[customers]);
 const customerGroups=useMemo(()=>Array.from(new Set(Array.from(customerGroupById.values()).filter(Boolean))).sort((a,b)=>a.localeCompare(b,'pt-BR')),[customerGroupById]);
 const postedTx=useMemo(()=>tx.filter(x=>x.status==='posted'),[tx]);
 const purchases=postedTx.filter(x=>x.type==='sale').reduce((s,x)=>s+Number(x.amount||0),0), payments=postedTx.filter(x=>['payment','credit'].includes(x.type)).reduce((s,x)=>s+Number(x.amount||0),0);
 const reportRows=useMemo(()=>report.map(r=>({...r,balance:Number(r.balance||0),purchases:Number(r.purchases||0),payments:Number(r.payments_and_credits||0)})),[report]);
 const filteredReportTx=useMemo(()=>tx.filter(x=>{
   if(!['sale','payment','credit'].includes(x.type))return false;
   if(reportFilters.customer_id && x.customer_id!==reportFilters.customer_id)return false;
   if(reportFilters.customer_group && customerGroupById.get(x.customer_id)!==reportFilters.customer_group)return false;
   if(reportFilters.from && x.transaction_date<reportFilters.from)return false;
   if(reportFilters.to && x.transaction_date>reportFilters.to)return false;
   if(reportFilters.kind==='sales' && x.type!=='sale')return false;
   if(reportFilters.kind==='payments' && !['payment','credit'].includes(x.type))return false;
   return true;
 }),[tx,reportFilters,customerGroupById]);
 const reportSummary=useMemo(()=>filteredReportTx.reduce((acc,x)=>{if(x.status!=='posted')return acc;const amount=Number(x.amount||0);if(x.type==='sale')acc.purchases+=amount;else if(['payment','credit'].includes(x.type))acc.payments+=amount;return acc},{purchases:0,payments:0}),[filteredReportTx]);
 const openBalances=useMemo(()=>reportRows.filter(r=>(!reportFilters.customer_id||r.customer_id===reportFilters.customer_id)&&(!reportFilters.customer_group||customerGroupById.get(r.customer_id)===reportFilters.customer_group)&&r.balance>0),[reportRows,reportFilters.customer_id,reportFilters.customer_group,customerGroupById]);
 function updateReportFilter(key,value){setReportFilters(prev=>key==='customer_group'?({...prev,customer_group:value,customer_id:''}):key==='customer_id'?({...prev,customer_id:value,customer_group:''}):({...prev,[key]:value}))}
 function clearReportFilters(){setReportFilters(emptyReportFilters)}
 if(!session)return <main className="login"><form className="loginbox" onSubmit={login}><div className="logo">SANY <span>Embalagens</span></div><p className="muted">Acesso ao sistema financeiro</p><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required /></label><label>Senha<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required /></label><button className="primary">Entrar</button>{error&&<p className="error">{error}</p>}</form></main>;
 return <div className="app"><aside><div className="logo">SANY <span>Embalagens</span></div><small>Sistema financeiro</small>{[['dash','Painel'],['launch','Novo lançamento'],['clients','Clientes'],['reports','Relatórios']].map(([id,label])=><button className={page===id?'nav active':'nav'} onClick={()=>setPage(id)} key={id}>{label}</button>)}<button className="logout" onClick={()=>supabase.auth.signOut()}>Sair</button></aside><main className="main"><header><div><h1>{({dash:'Painel',launch:'Novo lançamento',clients:'Clientes',reports:'Relatórios'})[page]}</h1><span>{session.user.email}</span></div></header>
 {page==='dash'&&<><div className="grid"><Metric label="Clientes ativos" value={customers.length}/><Metric label="Compras" value={money(purchases)}/><Metric label="Pagamentos" value={money(payments)}/><Metric label="Saldo a receber" value={money(purchases-payments)}/></div><Card title="Últimos lançamentos"><Table rows={tx.filter(x=>['sale','payment','credit'].includes(x.type)).slice(0,15)} names={names} onEdit={openEditTransaction} onDelete={cancelTransaction}/></Card></>}
 {page==='launch'&&<Card title="Novo lançamento"><form onSubmit={save} className="form"><label>Cliente<select value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})}><option value="">Selecione</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Tipo<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="sale">Compra</option><option value="payment">Pagamento</option><option value="credit">Crédito</option></select></label><label>Valor<input type="number" step="0.01" min="0" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Forma<select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}><option value="credit">Conta</option><option value="pix">PIX</option><option value="cash">Dinheiro</option><option value="card">Cartão</option><option value="check">Cheque</option><option value="transfer">Transferência</option></select></label><label className="wide">Descrição<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="primary">Salvar lançamento</button>{error&&<p className="error">{error}</p>}</form></Card>}
 {page==='clients'&&<Card title="Clientes" actions={<button className="primary" onClick={openNewCustomer}>+ Adicionar cliente</button>}><TableClients rows={customers} report={report} onEdit={openEditCustomer} onHide={hideCustomer}/></Card>}
 {page==='reports'&&<Reports filters={reportFilters} customers={customers} groups={customerGroups} transactions={filteredReportTx} summary={reportSummary} openBalances={openBalances} names={reportNames} onFilter={updateReportFilter} onClear={clearReportFilters} onEdit={openEditTransaction} onDelete={cancelTransaction}/>} 
 {transactionModal&&<div className="modalbackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)closeTransactionModal()}}><form className="modal" onSubmit={saveTransaction}><div className="modalhead"><h2>Editar lançamento</h2><button type="button" className="iconbutton" onClick={closeTransactionModal}>×</button></div><div className="customerform"><label>Cliente<select value={transactionForm.customer_id} onChange={e=>setTransactionForm({...transactionForm,customer_id:e.target.value})} required><option value="">Selecione</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Data<input type="date" value={transactionForm.transaction_date} onChange={e=>setTransactionForm({...transactionForm,transaction_date:e.target.value})} required/></label><label>Tipo<select value={transactionForm.type} onChange={e=>setTransactionForm({...transactionForm,type:e.target.value})}><option value="sale">Compra</option><option value="payment">Pagamento</option><option value="credit">Crédito</option></select></label><label>Valor<input type="number" step="0.01" min="0" value={transactionForm.amount} onChange={e=>setTransactionForm({...transactionForm,amount:e.target.value})} required/></label><label>Forma<select value={transactionForm.payment_method} onChange={e=>setTransactionForm({...transactionForm,payment_method:e.target.value})}><option value="credit">Conta</option><option value="pix">PIX</option><option value="cash">Dinheiro</option><option value="card">Cartão</option><option value="check">Cheque</option><option value="transfer">Transferência</option></select></label><label className="wide">Descrição<input value={transactionForm.description} onChange={e=>setTransactionForm({...transactionForm,description:e.target.value})}/></label></div>{error&&<p className="error">{error}</p>}<div className="modalactions"><button type="button" className="secondary" onClick={closeTransactionModal}>Cancelar</button><button className="primary">Salvar alterações</button></div></form></div>}
 {customerModal&&<div className="modalbackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)closeCustomerModal()}}><form className="modal" onSubmit={saveCustomer}><div className="modalhead"><h2>{editingCustomer?'Editar cliente':'Novo cliente'}</h2><button type="button" className="iconbutton" onClick={closeCustomerModal}>×</button></div><div className="customerform"><label>Nome<input autoFocus value={customerForm.name} onChange={e=>setCustomerForm({...customerForm,name:e.target.value})} required/></label><label>Nome da loja<input value={customerForm.store_name} onChange={e=>setCustomerForm({...customerForm,store_name:e.target.value})}/></label><label>CPF/CNPJ<input value={customerForm.document} onChange={e=>setCustomerForm({...customerForm,document:e.target.value})}/></label><label>Telefone<input value={customerForm.phone} onChange={e=>setCustomerForm({...customerForm,phone:e.target.value})}/></label><label>Limite de crédito<input type="number" min="0" step="0.01" value={customerForm.credit_limit} onChange={e=>setCustomerForm({...customerForm,credit_limit:e.target.value})}/></label><label className="wide">Observações<textarea value={customerForm.notes} onChange={e=>setCustomerForm({...customerForm,notes:e.target.value})}/></label></div>{error&&<p className="error">{error}</p>}<div className="modalactions"><button type="button" className="secondary" onClick={closeCustomerModal}>Cancelar</button><button className="primary">{editingCustomer?'Salvar alterações':'Adicionar cliente'}</button></div></form></div>}
 {loading&&<div className="loading">Atualizando dados…</div>}</main></div>
}
function Reports({filters,customers,groups,transactions,summary,openBalances,names,onFilter,onClear,onEdit,onDelete}){const openMode=filters.kind==='open';const filteredBalance=summary.purchases-summary.payments;return <div className="reportsPage"><Card title="Filtros"><div className="reportfilters"><label>De<input type="date" value={filters.from} onChange={e=>onFilter('from',e.target.value)}/></label><label>Até<input type="date" value={filters.to} onChange={e=>onFilter('to',e.target.value)}/></label><label>Cliente / Rede<select value={filters.customer_group ? `group:${filters.customer_group}` : filters.customer_id} onChange={e=>{const value=e.target.value;if(value.startsWith('group:')){onFilter('customer_group',value.slice(6));onFilter('customer_id','')}else{onFilter('customer_group','');onFilter('customer_id',value)}}}><option value="">Todos os clientes</option>{groups.map(g=><option key={`group-${g}`} value={`group:${g}`}>{g} — todas as lojas</option>)}<option disabled>──────── Lojas individuais ────────</option>{customers.map(c=><option key={c.id} value={c.id}>{c.store_name||c.name}</option>)}</select></label><label>Mostrar<select value={filters.kind} onChange={e=>onFilter('kind',e.target.value)}><option value="all">Todos os lançamentos</option><option value="sales">Somente compras</option><option value="payments">Somente pagamentos</option><option value="open">Em aberto</option></select></label><button className="secondary clearfilters" onClick={onClear}>Limpar filtros</button></div></Card><div className="grid reportgrid"><Metric label={openMode?'Compras no período':'Compras filtradas'} value={money(summary.purchases)}/><Metric label={openMode?'Pagamentos no período':'Pagamentos filtrados'} value={money(summary.payments)}/><Metric label={openMode?'Saldo no período':'Saldo filtrado'} value={money(filteredBalance)}/><Metric label="Lançamentos" value={openMode?openBalances.length:transactions.length}/></div><Card title={openMode?'Clientes com saldo em aberto':'Lançamentos do relatório'}>{openMode?<OpenBalanceTable rows={openBalances}/>:<Table rows={transactions} names={names} onEdit={onEdit} onDelete={onDelete}/>}</Card></div>}
function Metric({label,value}){return <div className="metric"><small>{label}</small><strong>{value}</strong></div>}
function Card({title,actions,children}){return <section className="card"><div className="cardhead"><h2>{title}</h2>{actions}</div>{children}</section>}
function Table({rows,names,onEdit,onDelete}){return <div className="tablewrap"><table><thead><tr><th>Data</th><th>Cliente</th><th>Tipo</th><th>Forma</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id} className={x.status!=='posted'?'cancelled-row':''}><td>{date(x.transaction_date)}</td><td>{names.get(x.customer_id)||'—'}</td><td>{typeLabel(x.type)}</td><td>{methodLabel(x.payment_method)}</td><td>{money(x.amount)}</td><td><span className={x.status==='posted'?'status-badge active':'status-badge cancelled'}>{statusLabel(x.status)}</span></td><td>{x.status==='posted'?<div className="rowactions"><button className="secondary small" onClick={()=>onEdit(x)}>Editar</button><button className="danger small" onClick={()=>onDelete(x)}>Cancelar</button></div>:<span className="muted">—</span>}</td></tr>):<tr><td colSpan="7" className="empty">Nenhum lançamento encontrado com esses filtros.</td></tr>}</tbody></table></div>}
function OpenBalanceTable({rows}){return <div className="tablewrap"><table><thead><tr><th>Cliente</th><th>Compras</th><th>Pagamentos</th><th>Saldo em aberto</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.customer_id}><td><strong>{r.customer_name}</strong></td><td>{money(r.purchases)}</td><td>{money(r.payments)}</td><td><strong>{money(r.balance)}</strong></td></tr>):<tr><td colSpan="4" className="empty">Nenhum cliente com saldo em aberto.</td></tr>}</tbody></table></div>}
function TableClients({rows,report,onEdit,onHide}){const m=new Map(report.map(x=>[x.customer_id,x.balance]));return <div className="tablewrap"><table><thead><tr><th>Cliente</th><th>Telefone</th><th>Limite</th><th>Saldo</th><th>Ações</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><strong>{c.name}</strong>{c.store_name&&<small className="subtext">{c.store_name}</small>}</td><td>{c.phone||'—'}</td><td>{money(c.credit_limit)}</td><td>{money(m.get(c.id)||0)}</td><td><div className="rowactions"><button className="secondary small" onClick={()=>onEdit(c)}>Editar</button><button className="danger small" onClick={()=>onHide(c)}>Ocultar</button></div></td></tr>)}</tbody></table></div>}
